name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"

jobs:
  extract-env:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.extract-env.outputs.ENV_PART }}
    steps:
    - name: Extract 'env' part from GitHub Ref
      id: extract-env
      run: |
        version=$GITHUB_REF_NAME
        env_part="${version##*-}"
        echo "Env Part: $env_part"
        echo "ENV_PART=$env_part" >> $GITHUB_OUTPUT
  buildAndDeployClient:
    name: Test vars from environment
    runs-on: ubuntu-latest
    needs: extract-env
    environment: ${{needs.extract-env.outputs.output1}}
    env:
      SECRET: ${{ vars.SECRE }}
    steps:
      - name: Print SECRET
        run: |
          echo "KEY: $SECRET"
          echo ${{needs.extract-env.outputs.output1}}
