name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"

jobs:
  extract-env:
    runs-on: ubuntu-latest
    steps:
    - name: Extract 'env' part from GitHub Ref
      id: extract-env
      run: |
        version=refs/head/0.0.0-dev
        env_part="${version##*-}"
        echo "Env Part: $env_part"
        echo "env_part={env_part}" >> $GITHUB_OUTPUT
  buildAndDeployClient:
    name: Test secrets from environment
    runs-on: ubuntu-latest
    needs: extract-env
    environment: ${jobs.extract-env.outputs.env_part}}
    env:
      SECRET: ${{ secrets.SECRE }}  # Correct syntax for accessing a secret
      ENV_PART: ${{ secrets.env_part }}
    steps:
      - name: Print SECRET
        run: |
          echo KEY: $SECRET
          echo env_part: $ENV_PART

        # version=$GITHUB_REF_NAME