name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"
# env:
#   MY_ENV: ${{ github.ref =~ "[0-9]+.[0-9]+.[0-9]+-prd" && 'prd' || github.ref =~ "[0-9]+.[0-9]+.[0-9]+-dev" && 'dev' || '' }}

jobs:
  # extract-dev:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Extract 'dev' part from GitHub Ref
  #     id: extract-dev
  #     run: |
  #       version=refs/head/0.0.1-prd
  #       dev_part="${version##*-}"
  #       echo "Dev Part: $dev_part"
  #       echo "##[set-output name=dev_part]${dev_part}"
  buildAndDeployClient:
    name: Test secrets from environment
    needs: extract-dev
    runs-on: ubuntu-latest
    environment: ${github.ref##*-}
    env:
      SECRET: ${{ secrets.SECRE }}  # Correct syntax for accessing a secret
    steps:
      - name: Print SECRET
        run: |
          echo KEY: '$SECRET'
