name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"

jobs:
  extract-env:
    runs-on: ubuntu-latest
    outputs:
      env_secrets: ${{ steps.extract-env.outputs.ENV_PART }}
    steps:
    - name: Extract 'env' part from GitHub Ref
      id: extract-env
      run: |
        version=$GITHUB_REF_NAME
        env_part="${version##*-}"
        echo "ENV_PART: $env_part"
        echo "ENV_PART=$env_part-tag" >> $GITHUB_OUTPUT

  buildAndDeploy:
    name: Build & deploy
    needs: extract-env
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
    with:
      ENV_PART: ${{needs.extract-env.outputs.env_secrets}}
