name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"

jobs:
  buildAndDeployClient:
    name: Test secrets from environment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        environment: [dev, prd]
    environment: ${{ matrix.environment }}
    env:
      SECRET: ${{ secrets.SECRE }}  # Correct syntax for accessing a secret
    steps:
      - name: Print SECRET
        run: |
          echo KEY: '$SECRET'
