name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"

jobs:
  testing:
    name: Test secrets from environment
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${GITHUB_REF_NAME##*-}
      SECRET: ${{ secrets.SECRE }}
    steps:
      - name: Print SECRET and Environment
        run: |
          echo "SECRET: $SECRET"
          echo "Environment: $ENVIRONMENT"
