name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"

jobs:
  set-tag-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Extract last part of tag
        id: extract-tag
        run: |
          tag=$GITHUB_REF
          tag_name="${tag##*/}"
          echo "Tag Name: $tag_name"
          echo "##[set-output name=tag_name]${tag_name}"

  buildAndDeployClient:
    name: Test secrets from environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ steps.extract-tag.outputs.tag_name }}
    env:
      SECRET: ${{ secrets.SECRE }}  # Correct syntax for accessing a secret
    steps:
      - name: Print SECRET
        run: |
          echo "Environment Name: ${{ steps.extract-tag.outputs.tag_name }}"
      - name: Print SECRET
        run: |
          echo KEY: '$SECRET'
