name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"

jobs:
  extract-env:
    runs-on: ubuntu-latest
    steps:
    - name: Extract 'env' part from GitHub Ref
      id: extract-env
      run: |
        version=$GITHUB_REF_NAME
        env_part="${version##*-}"
        echo "Env Part: $env_part"
        echo "ENV_PART=$env_part" >> $GITHUB_ENV
  buildAndDeployClient:
    name: Test secrets from environment
    runs-on: ubuntu-latest
    needs: extract-env
    environment: $ENV_PART
    env:
      SECRET: ${{ secrets.SECRE }}}
    steps:
      - name: Print SECRET
        run: |
          echo "KEY: $SECRET"
          echo "env_part: $ENV_PART"
