name: Build & Deploy

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-dev"
      - "[0-9]+.[0-9]+.[0-9]+-prd"
env:
  MY_ENV: ${{ github.ref =~ "[0-9]+.[0-9]+.[0-9]+-prd" && 'prd' || github.ref =~ "[0-9]+.[0-9]+.[0-9]+-dev" && 'dev' || '' }}

jobs:
  buildAndDeployClient:
    name: Test secrets from environment
    runs-on: ubuntu-latest
    environment: ${{ vars.MY_ENV }}
    env:
      SECRET: ${{ secrets.SECRE }}  # Correct syntax for accessing a secret
    steps:
      - name: Print SECRET
        run: |
          echo KEY: '$SECRET'
