name: Build & Deploy

on:
  workflow_call: 
    inputs:
      envir:
        required: true
        type: string

env:
  BUILD_TARGET: Standalon
  LA: ${{ secrets.LALALA}}
  S: ${{ vars.SECRE }}
  env: ${{secrets.ENV_PART}}

jobs:
    buildAndDeploy:
      name: Build & deploy
      environment: ${{inputs.envir}}
      runs-on: ubuntu-latest
      steps:  
        - name: Echo secre
          run: echo "$SECRE"
        - name: Echo secre2
          run: echo "${{secrets.SECRE}}"
        - name: Echo lala
          run: echo "$LALALA"
        - name: Echo lala2
          run: echo "${{secrets.LALALA}}"
        - name: Echo2
          run: echo "$BUILD_TARGET"
        - name: Echhooo envir
          run: echo "${{inputs.envir}}"
        - name: Echhooo222
          run: echo "$SEC"
          env:
            SEC: ${{needs.extract-env-outputs.env_secrets}}
        - name: aaa
          run: echo "$env"

